### ISSUE TITLE
cloned locally and not working

### ISSUE THREAD

**Issue by kthouz** [agordon/d3export_demo#10]
I am trying to use your application locally and it doesn't work.
When I copy relevant pieces into my app, I get 

Not Found

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by agordon** [comment]
Hi,

I'm not sure what you mean by "locally". This demo (and it's only a demo, proof-of-concept) requires a web server that can execute CGI scripts.
Did you setup such web servers and configured it to run the `download.pl` file as CGI ?

**Comment by mkermani** [comment]
Hello,
I was wondering if this saving procedure can be performed without web server? I am developing a tool which generates a sankey using d3js library and I would like to save it to pdf.
Many thanks in advance,

**Comment by agordon** [comment]
I'm not up-to-date with javascript/client-side PDF technologies since d3_export was developed (in 2014).
Perhaps https://github.com/MrRio/jsPDF has gotten much much better and can do it entirely in client-side.

If SVG is sufficient, it's already possible.
If PNG is sufficient, try these: https://github.com/krunkosaurus/simg , http://techslides.com/save-svg-as-an-image
