### ISSUE TITLE
Update readme with best modern alternative

### ISSUE THREAD

**Issue by hugolpz** [agordon/d3export_demo#12]
As the project have been inactive for past 4 years, would you recommend another library for doing that same task ? Any info ? Please write it in your readme so netizens landing on your project (still highly visible) can smoothly be redirected with the best lib of 2017~2018.
It would help the community to use the best tools :+1:

**Comment by agordon** [comment]
Hello @hugolpz ,

There have been no updates because no updates are needed. It is a technical demo (as indicate by the name), and it still works perfectly. It demonstrates how to use 'rsvg-convert' with a simple CGI to download PDFs - none of that changed in the last 4 years (except rsvg-convert was probably improved by its developers).

regards,
gordon
